data:
  n_classes: 5                            # Causalcall (A, C, G, U, blank)
  window_size: 512                        # Causalcall

train:
  batch_size: 256                         # Causalcall
  n_epochs: 100                           # Experimental
  n_folds: 10                             # Experimental
  val_freq: 1                             # Experimental
  opt:
    max_steps: 200000                       # Causalcall
    boundaries: [0.03,0.07,0.25,0.5,0.7]    # Causalcall
    init_rate: 0.004                        # Causalcall
    decays: [0.4,0.2,0.1,0.06,0.03,0.01]    # Causalcall

model:
  relu_units: 128                         # Causalcall
  softmax_units: 5                        # Causalcall
  timesteps: 512                          # Causalcall (size of window)
  tcn:
    nb_filters: 256                       # Causalcall
    kernel_size: 3                        # Causalcall
    nb_stacks: 1                          # Default
    dilations: [1,2,4,8,16]               # Causalcall
    padding: 'causal'                     # Default
    use_skip_connections: False           # Default
    dropout_rate: 0.0                     # Default
    return_sequences: True                # Default
    activation: 'relu'                    # Default
    kernel_initializer: 'he_normal'       # Default
    use_batch_norm: False                 # Default